# Generated by Django 3.2.2 on 2021-05-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("zip_code", models.CharField(max_length=12)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("document", models.CharField(max_length=14)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "creditor",
            },
        ),
        migrations.CreateModel(
            name="DebtorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("zip_code", models.CharField(max_length=12)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("document", models.CharField(max_length=14)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "debtor",
            },
        ),
    ]
